"""TikTok parsing module.

Adapted from Zeeschuimer's modules/tiktok.js
(https://github.com/digitalmethodsinitiative/zeeschuimer),
Copyright (c) Stijn Peeters, Mozilla Public License 2.0.

Modifications for LaclauGPT (2026):
- translated capture() and map_item() from JavaScript to Python;
- capture() gains a raw-payload hook: callers may pass the already-parsed
  JSON object instead of a response string (used by the HAR/CDP driver);
- map_item() emits plain dicts with LaclauGPT normalised field names
  instead of 4CAT's MappedItem objects;
- the upstream "auto-generated by 4cat map_item sync" block is kept in
  structure (field-for-field) so upstream updates remain diffable.

This file is MPL-2.0 like the upstream it adapts; see modules/README.md.
"""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

MODULE_NAME = "TikTok (posts)"
DOMAIN = "tiktok.com"

# Embedded-JSON sigils from upstream (SIGI_STATE and the newer
# __UNIVERSAL_DATA_FOR_REHYDRATION__ payload).
_SIGIL_START = re.compile(
    r"(window\['SIGI_STATE'\]\s*=\s*|<script id=\"SIGI_STATE\" type=\"application/json\">)")
_SIGIL_END = re.compile(r"(;\s*window\['SIGI_RETRY'\]\s*=\s*|</script>)")
_UDR_SCRIPT = re.compile(
    r"<script[^>]+id=\"__UNIVERSAL_DATA_FOR_REHYDRATION__\"[^>]*type=[\"']application/json[\"'][^>]*>"
    r"([\s\S]*?)</script>", re.IGNORECASE)


def capture(response: Any, source_platform_url: str, source_url: str) -> list[dict]:
    """Extract TikTok item dicts from one captured response.

    `response` may be a JSON string, an HTML page with embedded JSON, or an
    already-parsed dict (the driver shortcut). Returns native item dicts
    (ItemModule/itemList shapes); normalization happens in map_item().
    """
    domain = (source_platform_url.split("/")[2] if "//" in source_platform_url
              else source_platform_url).lower().replace("www.", "")
    if domain != "tiktok.com":
        return []

    # already-parsed payload shortcut (CDP/HAR driver)
    if isinstance(response, dict):
        data = response
    else:
        from_embed = False
        if isinstance(response, str) and _SIGIL_START.search(response):
            response = _SIGIL_START.split(response)[2]
            if not _SIGIL_END.search(response):
                return []
            response = _SIGIL_END.split(response)[0]
            from_embed = True

        if not from_embed and isinstance(response, str) and "<script" in response:
            udr = _UDR_SCRIPT.search(response)
            if udr and udr.group(1):
                try:
                    ud = json.loads(udr.group(1))
                    scope = ud and ud.get("__DEFAULT_SCOPE__")
                    updated = scope and scope.get("webapp.updated-items")
                    if isinstance(updated, list):
                        return [x for x in updated if not (x or {}).get("liveRoomInfo")]
                    single = (scope or {}).get("webapp.video-detail", {}).get(
                        "itemInfo", {}).get("itemStruct")
                    if single:
                        return [single]
                except (json.JSONDecodeError, AttributeError, TypeError):
                    pass  # fall through to other strategies

        if not response:
            return []
        try:
            data = json.loads(response)
        except (json.JSONDecodeError, TypeError):
            return []

    # preload responses carry items that may never be displayed; upstream
    # ignores them and so do we (avoid collecting content the visitor
    # never saw)
    if "api/preload/" in (source_url or ""):
        return []

    if "ItemModule" in data:
        return [x for x in data["ItemModule"].values()
                if not x.get("liveRoomInfo")]
    if "itemList" in data:
        return [x for x in data["itemList"] if not x.get("liveRoomInfo")]
    if "item_list" in data:
        return [x for x in data["item_list"] if not x.get("liveRoomInfo")]
    if "data" in data:
        # search "top results" (non-video tab) shape
        rows = list((data["data"] or {}).values())
        items = [x.get("item") for x in rows
                 if isinstance(x, dict) and "item" in x and "type" in x]
        known = ("id", "desc", "createTime", "music")
        return [it for it in items
                if isinstance(it, dict)
                and all(k in it for k in known)
                and "liveRoomInfo" not in it]
    return []


def map_item(post: dict, metadata: dict | None = None) -> dict:
    """Normalise one native TikTok item into a flat LaclauGPT record.

    Field-for-field port of the upstream map_item block (4CAT sync),
    adapted to plain Python dicts.
    """
    metadata = metadata or {}
    challenges = [ch["title"] for ch in (post.get("challenges") or [])
                  if isinstance(ch, dict) and ch.get("title")]
    hashtags = [extra["hashtagName"] for extra in (post.get("textExtra") or [])
                if isinstance(extra, dict) and extra.get("hashtagName")]

    labels = ",".join(post["diversificationLabels"]) if isinstance(
        post.get("diversificationLabels"), list) else ""

    user_nickname = user_fullname = user_thumbnail = ""
    author = post.get("author")
    if isinstance(author, dict):
        user_nickname = author.get("uniqueId") or ""
        user_fullname = author.get("nickname") or ""
        user_thumbnail = author.get("avatarThumb") or ""
    elif author is not None:
        # embedded JSON objects carry a flat author string
        user_nickname = author or ""
        user_fullname = post.get("nickname") or ""

    video = post.get("video") or {}
    thumbnail_options: list[str] = []
    share_cover = video.get("shareCover")
    if isinstance(share_cover, list) and share_cover:
        thumbnail_options.append(share_cover[-1])
    elif isinstance(share_cover, str) and share_cover:
        thumbnail_options.append(share_cover)
    if video.get("cover"):
        thumbnail_options.append(video["cover"])

    now = int(datetime.now(timezone.utc).timestamp())
    valid_thumbs = []
    for url in thumbnail_options:
        try:
            expires = int(urlparse(url).query.split("x-expires=")[1].split("&")[0])
        except (ValueError, IndexError, AttributeError):
            continue
        if expires >= now:
            valid_thumbs.append(url)
    thumbnail_url = valid_thumbs[-1] if valid_thumbs else ""

    create_time = post.get("createTime")
    try:
        unix_ts = int(str(create_time))
    except (TypeError, ValueError):
        unix_ts = 0
    stats = post.get("stats") or {}
    author_stats = post.get("authorStats") or {}
    duet_info = post.get("duetInfo") or {}

    return {
        "collected_from_url": metadata.get("source_platform_url", ""),
        "id": str(post.get("id", "")),
        "thread_id": str(post.get("id", "")),
        "author": user_nickname,
        "author_full": user_fullname,
        "author_followers": author_stats.get("followerCount", ""),
        "author_likes": author_stats.get("diggCount", ""),
        "author_videos": author_stats.get("videoCount", ""),
        "author_avatar": user_thumbnail,
        "body": post.get("desc") or "",
        "stickers": "\n".join(
            " ".join(t for t in (s.get("stickerText") or []) if t)
            for s in (post.get("stickersOnItem") or [])
            if isinstance(s, dict)),
        "timestamp": datetime.fromtimestamp(unix_ts, timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ") if unix_ts else "",
        "unix_timestamp": unix_ts,
        "is_duet": "yes" if str(duet_info.get("duetFromId") or "0") != "0" else "no",
        "is_ad": "yes" if post.get("isAd") else "no",
        "is_paid_partnership": "yes" if post.get("adAuthorization") else "no",
        "is_sensitive": "yes" if post.get("maskType") == 3 else "no",
        "is_photosensitive": "yes" if post.get("maskType") == 4 else "no",
        "music_name": (post.get("music") or {}).get("title", ""),
        "music_id": str((post.get("music") or {}).get("id", "")),
        "music_url": (post.get("music") or {}).get("playUrl", ""),
        "music_thumbnail": (post.get("music") or {}).get("coverLarge", ""),
        "music_author": (post.get("music") or {}).get("authorName", ""),
        "video_url": video.get("downloadAddr", ""),
        "tiktok_url": f"https://www.tiktok.com/@{user_nickname}/video/{post.get('id', '')}",
        "thumbnail_url": thumbnail_url,
        "likes": stats.get("diggCount"),
        "comments": stats.get("commentCount"),
        "shares": stats.get("shareCount"),
        "plays": stats.get("playCount"),
        "hashtags": ",".join(hashtags),
        "challenges": ",".join(challenges),
        "diversification_labels": labels,
        "location_created": post.get("locationCreated") or "",
        "effects": ",".join(e["name"] for e in (post.get("effectStickers") or [])
                            if isinstance(e, dict) and e.get("name")),
        "warning": ",".join(w["text"] for w in (post.get("warnInfo") or [])
                            if isinstance(w, dict) and w.get("text")),
    }